apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o /Users/yurikrupnik/github/nx-playground/k8s/databases/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: arangodb
  name: arangodb
spec:
  ports:
    - name: "8529"
      port: 8529
      targetPort: 8529
  selector:
    io.kompose.service: arangodb
