apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o /Users/yurikrupnik/github/nx-playground/k8s/databases/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: milvus
  name: milvus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: milvus
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml -o /Users/yurikrupnik/github/nx-playground/k8s/databases/
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: milvus
    spec:
      containers:
        - args:
            - milvus
            - run
            - standalone
          env:
            - name: ETCD_ENDPOINTS
              value: milvus-etcd:2379
            - name: MINIO_ADDRESS
              value: milvus-minio:9000
          image: milvusdb/milvus:v2.3.3
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:9091/healthz
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 20
          name: milvus
          ports:
            - containerPort: 19530
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
            - containerPort: 19121
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/milvus
              name: milvus-data
      restartPolicy: Always
      volumes:
        - name: milvus-data
          persistentVolumeClaim:
            claimName: milvus-data
