apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o /Users/yurikrupnik/github/nx-playground/k8s/databases/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: neo4j
  name: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: neo4j
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml -o /Users/yurikrupnik/github/nx-playground/k8s/databases/
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: neo4j
    spec:
      containers:
        - env:
            - name: NEO4J_AUTH
              value: neo4j/password123
            - name: NEO4J_PLUGINS
              value: '["apoc"]'
            - name: NEO4J_dbms_memory_heap_initial__size
              value: 512m
            - name: NEO4J_dbms_memory_heap_max__size
              value: 1G
            - name: NEO4J_dbms_security_procedures_unrestricted
              value: apoc.*
          image: neo4j:5-community
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:7474
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 10
          name: neo4j
          ports:
            - containerPort: 7474
              protocol: TCP
            - containerPort: 7687
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: neo4j-data
            - mountPath: /logs
              name: neo4j-logs
      restartPolicy: Always
      volumes:
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: neo4j-data
        - name: neo4j-logs
          persistentVolumeClaim:
            claimName: neo4j-logs
