apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o /Users/yurikrupnik/github/nx-playground/k8s/databases/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: qdrant
  name: qdrant
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: qdrant
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml -o /Users/yurikrupnik/github/nx-playground/k8s/databases/
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: qdrant
    spec:
      containers:
        - env:
            - name: QDRANT__LOG_LEVEL
              value: INFO
            - name: QDRANT__SERVICE__GRPC_PORT
              value: "6334"
            - name: QDRANT__SERVICE__HTTP_PORT
              value: "6333"
          image: qdrant/qdrant:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:6333/healthz
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 10
          name: qdrant
          ports:
            - containerPort: 6333
              protocol: TCP
            - containerPort: 6334
              protocol: TCP
          volumeMounts:
            - mountPath: /qdrant/config
              name: qdrant-claim0
      restartPolicy: Always
      volumes:
        - name: qdrant-claim0
          persistentVolumeClaim:
            claimName: qdrant-claim0
