apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: mydatabase-schema
  namespace: dbs
spec:
  url: "postgres://myuser:mypassword@postgres.dbs.svc.cluster.local:5432/mydatabase?sslmode=disable"
  schema:
    configMapKeyRef:
      key: schema.sql
      name: mydatabase-schema
  policy:
    diff:
      skip:
        drop_schema: true
        drop_table: true
    lint:
      destructive:
        error: false
