apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zerg-shared-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: zerg-shared-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: app-secrets
        property: zerg-shared.database_url
