apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: zerg-dev

resources:
  - ../../base

namePrefix: dev-

# Dev: Allow destructive changes for rapid iteration
patches:
  - patch: |-
      - op: replace
        path: /spec/policy/lint/destructive/error
        value: false
      - op: replace
        path: /spec/policy/diff/skip/drop_column
        value: false
      - op: replace
        path: /spec/policy/diff/skip/drop_table
        value: false
    target:
      kind: AtlasSchema
      name: zerg-schema
