apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dbs

resources:
  - namespace.yaml
  - cluster.yaml
  - atlas-migration.yaml
  - migrations-configmap.yaml
  - scheduled-backup.yaml

# Common labels
labels:
  - pairs:
      app.kubernetes.io/part-of: dbs
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false

# Configuration
configMapGenerator:
  - name: db-config
    literals:
      - DATABASE_SCHEMA=public
