apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zerg-api-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: zerg-api-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: app-secrets
        property: zerg-api
