apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  # - service.yaml
  # - hpa.yaml

# configMapGenerator:
#   - name: shared-config
#     files:
#     - default.conf.template
# secretGenerator:
#   - name: dads
#     files:
#       - .env
#       - .env.example
#       - secrets.yaml
#       - secrets.json
#       - secrets.toml
