apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zerg-api-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: zerg-api-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: app-secrets
        property: zerg-api.jwt_secret
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: app-secrets
        property: zerg-api.google_client_id
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: app-secrets
        property: zerg-api.google_client_secret
    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        key: app-secrets
        property: zerg-api.github_client_id
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: app-secrets
        property: zerg-api.github_client_secret
    - secretKey: FLAGSMITH_ENVIRONMENT_KEY
      remoteRef:
        key: app-secrets
        property: zerg-api.flagsmith_environment_key
