apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zerg

resources:
  - ../../base
  - scaledobject.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env
        value:
          - name: GRPC_HOST
            value: "0.0.0.0"
          - name: GRPC_PORT
            value: "50051"
          - name: RUST_LOG
            value: "info"
          - name: QDRANT_URL
            value: "http://qdrant.dbs.svc.cluster.local:6334"
          - name: QDRANT_TIMEOUT_SECS
            value: "30"
    target:
      kind: Deployment
      name: zerg-vector
