apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zerg

resources:
  - ../../base

replicas:
  - name: zerg-email-nats
    count: 1

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: zerg-email-nats-config
    literals:
      - HEALTH_PORT=8081
      - SMTP_HOST=mailhog.dbs.svc.cluster.local
      - SMTP_PORT=1025
      - EMAIL_FROM_ADDRESS=noreply@zerg.local
      - EMAIL_FROM_NAME=Zerg Dev

secretGenerator:
  - name: zerg-email-nats-secrets
    literals:
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
