apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zerg

resources:
  - atlas-schema.yaml
  - schema-configmap.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: zerg
      app.kubernetes.io/managed-by: atlas-operator
