apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#resources:
#  - gateway.yaml
#  - monitoring-virtualservices.yaml
configMapGenerator:
  - name: proto-configs
    options:
      disableNameSuffixHash: true
    files:
      - apps/v1/users.proto
      - apps/v1/tasks.proto
