reorder_impl_items = true
reorder_imports = true
reorder_modules = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"

max_width = 100
use_small_heuristics = "Max"
wrap_comments = true
comment_width = 100

newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true
format_strings = true

imports_indent = "Block"
imports_layout = "Mixed"

fn_params_layout = "Tall"
fn_call_width = 80

trailing_comma = "Vertical"
trailing_semicolon = true

use_field_init_shorthand = true
force_explicit_abi = true

match_arm_blocks = true
match_block_trailing_comma = true

chain_width = 80
short_array_element_width_threshold = 10

remove_nested_parens = true
