apiVersion: v1
kind: Service
metadata:
  name: zerg-email-worker
spec:
  selector:
    app: zerg-email-worker
  ports:
    - protocol: TCP
      name: health
      port: 8081
      targetPort: 8081
  type: ClusterIP
