apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    otel:
      endpointAddress: "localhost:4317"
      isSecure: false
      protocol: grpc
  metrics:
    enabled: true
    rules:
      - name: dapr_runtime_component_request_count
        labels:
          - name: component
          - name: success
  logging:
    apiLogging:
      enabled: true
      obfuscateURLs: false
  features:
    - name: Resiliency
      enabled: true
    - name: ServiceInvocationStreaming
      enabled: true
  accessControl:
    defaultAction: allow
    trustDomain: "nx-playground"
