[package]
name = "zerg_mongo_api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true }
axum-helpers = { workspace = true }
chrono = { workspace = true }
color-eyre = { workspace = true }
core_config = { workspace = true }
database = { workspace = true, features = ["mongodb", "config"] }
domain_events = { workspace = true }
domain_items = { workspace = true }
eyre = { workspace = true }
mongodb = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
utoipa = { workspace = true }
uuid = { workspace = true }
