apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: zerg-web
  namespace: gateway
spec:
  parentRefs:
    - name: main-gateway
      namespace: gateway
      sectionName: https-exact
  hostnames:
    - "127.0.0.1.nip.io"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
#            value: /web
#      filters:
#        - type: URLRewrite
#          urlRewrite:
#            path:
#              type: ReplacePrefixMatch
#              replacePrefixMatch: /
      backendRefs:
        - name: zerg-web
          namespace: zerg
          port: 8080
