apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerg-web
  labels:
    app: zerg-web
#    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zerg-web
  template:
    metadata:
      labels:
        app: zerg-web
#        tier: frontend
    spec:
#      securityContext:
#        runAsNonRoot: true
#        runAsUser: 65534
#        fsGroup: 65534
      containers:
        - name: zerg-web
          image: yurikrupnik/zerg-web
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          env:
            - name: UPSTREAM_HOST
              valueFrom:
                configMapKeyRef:
                  key: upstream_host
                  name: proxy-envs
            - name: UPSTREAM_PORT
              valueFrom:
                configMapKeyRef:
                  key: upstream_port
                  name: proxy-envs
            - name: UPSTREAM_NAME
              valueFrom:
                configMapKeyRef:
                  key: upstream_name
                  name: proxy-envs
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
#          securityContext:
#            allowPrivilegeEscalation: false
#            runAsNonRoot: true
#            runAsUser: 101
#            runAsGroup: 101
#            capabilities:
#              drop:
#                - ALL
#              add:
#                - NET_BIND_SERVICE
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/templates
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: proxy-envs
          configMap:
            name: proxy-envs
      restartPolicy: Always
