apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - configmap.yaml
  - deployment.yaml
  - service.yaml
#namespace: zerg
configMapGenerator:
  - name: nginx-config
    files:
      - default.conf.template
  - name: "proxy-envs"
    literals:
      - "upstream_host=zerg-api"
      - "upstream_port=8080"
      - "upstream_name=backend"
      - "upstream_path=/api"
