apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zerg-email-nats-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: zerg-email-nats-secrets
    creationPolicy: Owner
  data:
    - secretKey: SENDGRID_API_KEY
      remoteRef:
        key: app-secrets
        property: zerg-email-nats.sendgrid_api_key
    - secretKey: SENDGRID_FROM_EMAIL
      remoteRef:
        key: app-secrets
        property: zerg-email-nats.sendgrid_from_email
