apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

# Merge dev-specific config values
patches:
  - path: configmap-patches.yaml
    target:
      kind: ConfigMap
      name: zerg-shared-config

labels:
  - pairs:
      environment: development
