apiVersion: v1
kind: Service
metadata:
  name: zerg-email
spec:
  selector:
    app: zerg-email
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
