apiVersion: v1
kind: Service
metadata:
  name: zerg-email
spec:
  selector:
    app: zerg-email
  ports:
    - protocol: TCP
      name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP
